-- Legado: Doctor -> suppliers (154 registros)
-- Columnas origen: IdDoctor, Nombre, Telefono

INSERT INTO suppliers (id, code, name, phone, active, created_at) VALUES
  (gen_random_uuid(), '2018', 'ANA LAURA CORONA JIMENEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), '22', 'FLORERIA ADE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ADMIN', 'CESAR ROGELIO CORONADO BARCENAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AGS', 'UNITED AUTOS DE AGUSCALIENTES S DE RL DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AGUA', 'JUBILEO AZUL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AID', 'AIDA JUDITH SOTO TOVAR', '00', TRUE, NOW()),
  (gen_random_uuid(), 'AILEEN', 'AILEEN VANESSA OLVERA BENITEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AIRE ACOND', 'ERICK GARCIA LEON', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ALF', 'ALFONSO RODRIGUEZ PEREZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ALFONSO', 'ALFONSO PEREZ RODRIGUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ANFORA', 'PROVEEDOR ALMACENES ANFORA SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ANRO', 'ANGEL RODRIGUEZ PEREZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ARQCOP', 'ARQCOPROTECCION PERIMETRAL SA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ASTROS', 'JOSE ROBERTO MARQUEZ ISLAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ATLAS', 'LLANTERA ATLAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AUTO', 'AUTOMOTORES DE QRO SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'AUTODOC', 'AUTODOC SU CENTRO VEHICULAR DE SERV AUT Y VERFIC V', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BAMBI', 'EVA RESENDIZ RIOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BANDERAS', 'ALEJANDRA LOPEZ AGUILAR', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BARR', 'REFACCIONES Y SERVICIOS BARRERA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BERNABE', 'BERNABE TRUJILLO (INFLABLES JONABE)', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BLAN', 'BLANCA E. PAVON MORALES', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BOMBA', 'BOMBAS Y VALVULAS COTOSA SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BRAU', 'BRAULIO E. ROMO CRUZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'BRAULIO', 'BRAULIO E. ROMO CRUZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CALIX', 'CALIXTO TREJO RESENDIZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CANACAR', 'CAMARA NACIONAL DEL AUTOTRANSPORTE DE CARGA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CAT', 'MAQUINAS DIESEL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CECOM', 'CENTRO COMERCIAL CRUZ AZUL', '7737329201', TRUE, NOW()),
  (gen_random_uuid(), 'CESAR', 'CESAR JAVIER JIMENEZ GARCIA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CONST', 'LABORATORIO NACIONAL DE LA CONSTRUCCION', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CONTROL', 'ESTRATEGIA EMPRESARIAL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'COSTCO', 'AGS (COSTCO DE MEXICO SA)', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'CRU', 'CASA CRU SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DAN', 'DANUBIO TREJO VILLADONGA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DAVID', 'DAVID MAYA SOSA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DESINF', 'JUAN MANUEL SALGADO VAZQUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DIAG', 'CENTRO DE DIAGNOSTICO FISICO MECANICO DEL BAJIO SA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DIEM', 'DIEM COMERC Y PRESTADORA DE SERV EN MEDIO AMBIENTE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'DL', 'DELECO COMPUTO, OFICINA Y PAPELERIA', '7737321900', TRUE, NOW()),
  (gen_random_uuid(), 'DONKIN', 'EL DONKIN SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ENERGY', 'BRAVO ENERGY S DE RL DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ENRIQ', 'ENRIQUE SERRANO BENITEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ENRIQUE', 'ENRIQUE SERRANO BENITEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FELIXX', 'FELIX ALANIZ GRANADOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FER', 'FERNANDO GONZALEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FI', 'FIDEL ALTAMIRANO HERNÁNDEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FINANZAS', 'SECRETARIA DE FINANZAS PUBLICAS TULA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FLOR', 'SILVIANA HERNANDEZ MARTINEZ', '00', TRUE, NOW()),
  (gen_random_uuid(), 'FLORES', 'FLORERIA VANE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FUENTE', 'RESTAURANT LA FUENTE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'FUS', 'BENJAMIN HOWARD DAWE CERON', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'GAB', 'GABRIEL MERIÑO ZETINA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'GEN 2000', 'TEXTILES GENERACION 2000', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'GERA', 'GERARDO LEON GARCIA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'GRAFIC', 'COLOR GRAFICOS TULA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'GRAFICO', 'PUBLICIDAD GRAFICO AZUL SA DE CV', '7851023', TRUE, NOW()),
  (gen_random_uuid(), 'GUADA', 'GUADALUPE RODRIGUE PEREZ', '7737322408', TRUE, NOW()),
  (gen_random_uuid(), 'HD', 'INFOPROYECTOS HD SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'HIGINIO', 'HIGINIO LEON ANGELES', '7736805347', TRUE, NOW()),
  (gen_random_uuid(), 'ICATEL', 'ICATEL SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ISI', 'ISIDORO ISLAS RODRIGUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ISLA', 'RESTAURATE LA ISLA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'J ENRIQUE', 'JUAN ENRIQUE ZAMORA PAEZ', '123', TRUE, NOW()),
  (gen_random_uuid(), 'JAVIER', 'JAVIER CERVANTES SERRANO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JENNIE', 'JENNIE CERON CURIEL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JENNY', 'JENNY YOSELIN RODRIGUEZ MEDINA', '000', TRUE, NOW()),
  (gen_random_uuid(), 'JILO', 'EMISIONES JILOTEPEC S.A DE C.V.', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JILOTONER', 'ANGELINA MARTINEZ GARCIA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JM', 'JUAN MANUEL GARCIA CRUZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JOEL', 'JOEL VILLEDA HERNANDEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JOSEANG', 'JOSE ANGEL SALAZAR ESCARCEGA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'JUVE', 'JUVENCIO GARCIA HERNANDEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'KEN', 'KENWORTH DEL SUR', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'KEY', 'KEYTEL MARTINEZ SAN NICOLAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'LAB', 'LABORATORIO INDUSTRIAL AMBIENTAL SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'LPO', 'LIZBETH PAREDES OLVERA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'LUCY', 'LUCIA GONZALEZ ESCAMILLA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'LUGO', 'ALBERTO LUGO CORDERO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'LUIS', 'LUIS GERARDO RODRIGUEZ TOVAR', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MADCA', 'MARIA DEL CARMEN AGUIRRE NAVARRO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MANGUERAS', 'TOPILTZIN RESENDIZ OLGUIN', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MARC', 'MARCO ANTONIO LEON MARTIN', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MARCO', 'MARCO ANTONIO LEON MARTIN', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MARIO', 'CERRAJERIA MARIOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MARPA', 'MARPA DE PACHUCA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MARQUEZ', 'JESUS FERNANDO MARQUEZ HDEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MART', 'EQUIPOS CONTRA INCENDIO MART', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MATERIAL', 'PROYECTOS Y CONST DEL CENTRO DEL VALLE MOLE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MAX', 'MAX DARINEL REYES MONROY', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MAY', 'BLANCA PATRICIA CERON MONTUFAR', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MAYA', 'ALQUILADORA MAYA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MC', 'MECANICA BETOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MIADMIN', 'CESAR R CORONADO BARCENAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MIGUE', 'MIGUEL ANGEL ORTEGA REYES', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MIGUEL', 'MIGUEL ALONSO CRUZ ESCAMILLA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ML', 'MERCADO LIBRE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'MXSOL', 'MX SOLUCIONES SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'NARCI', 'NARCISA PEÑA CRUZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'NAUDA', 'NAUDA SAPI DE V', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ND', 'ND ACCESORIOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'NEGRITOS', 'JOSE MANUEL MARTINEZ LUJAN', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'OBCE', 'JUAN MIGUEL OBREGON CERON', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'OFD', 'OFFICE DEPOT', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'OFFICE', 'OFFICE DEPOT DE MEXICO SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'OPTIMA', 'TIENDAS ALKA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ORO', 'PAPEL ORO DEL CENTRO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'PAPELERIA', 'JILOTONER', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'PASTELERIA', 'GRUPO COMERCIAL ESTRELLA AZUL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'PATY', 'GABRIELA PATRICIA PONCE ESPARZA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'PH', 'PHC', '000', TRUE, NOW()),
  (gen_random_uuid(), 'PINGOL', 'PINGOL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'PROV', 'LUIS MANUEL PEÑA BARRERA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'QS COMPU', 'JOSE LUIS ROJAS TEJEDA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'RAFA', 'RAFAEL RODRIGUEZ RESENDIZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'RB', 'LABORATORIOS RB', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'REFAC', 'TRUCKING SUPPLIES MEXICO SA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'REFACCAN', 'REFACCIONES CANELLI SA DE CV', '7737336033', TRUE, NOW()),
  (gen_random_uuid(), 'RINCON', 'RESTAURANT FAMILIAR EL RINCON DE VILLA SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ROB', 'ROBERTO GUERRERO MONTALVO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'ROS', 'ROSALBA PAREDES RUBIO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'RUFO', 'RUFO ESTRADA FALCON', '000', TRUE, NOW()),
  (gen_random_uuid(), 'SAHAGID', 'SAHAGID E. HERNANDEZ MAGOS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SALON', 'SALON GRAN VICTORIA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SANDRA', 'SANDRA E.MEDINA VAZQUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SANTIAGO', 'SANTIAGO GARCIA JIMENEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SIL', 'EL RINCON SALUDABLE DE SIL', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SIMSA', 'SUMINISTROS INDUSTRIALES MANUFACTURERA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SIST', 'SISTEMAS COMPUTACIONALES Y PROY ARQUITECTONICOS SA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SITSA', 'SOLUCIIONES INTEGRALES PARA TRITURACION SAS', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SMARTNET', 'NOÉ SERGIO VERAZAS CRUZ', '773 7326263', TRUE, NOW()),
  (gen_random_uuid(), 'SN JOSE', 'CERAMIC AND MORE SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SOL', 'MARIA DEL SOL RAMIREZ SERRANO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SP', 'SUPER PAPELERA SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SU', 'SURTIDORA ELECTRICA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SUP', 'SUPER PAPELERA SA DE CV', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SURT', 'SURTIDORA ELECTRICA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'SURTIDORA', 'ANTONIO AVILA JUAREZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'TERE', 'TERESA VARELA VASQUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'TERESA', 'TERESA VARELA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'TONY', 'MARCO ANTONIO SANCHEZ RIVERA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'TULA', 'AUTOMOTRIZ TULA DE ALLENDE SA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'UMJ', 'UNIDAD MEDICA JUAREZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'UNION', 'UNION SERVICIOS PROFESIONALES', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'VIEYRA', 'CESAR VIEYRA SALGADO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'VIOLE', 'HERNANDEZ MENDOZA VIOLETA', '00', TRUE, NOW()),
  (gen_random_uuid(), 'VT', 'VERIFICACIONES TEPEJI', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'VV14', 'VERIFICENTRO VEHICULAR NO.14', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'WALDOS', 'WALDOS DOLAR MART DE MEXICO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'WW', 'VOLKSWAGEN TULA', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'XCE', 'EXCELENCIA AUTOMOTRIZ DEL NORTE', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'XX', 'CLARA GUADALUPE GARCIA RODRIGUEZ', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'YADIRA', 'YADIRA M DELGADILLO ROMO', NULL, TRUE, NOW()),
  (gen_random_uuid(), 'YARA', 'YARA GUADALUPE REDONDO FCO.', NULL, TRUE, NOW());
