-- Legado: Trabajador -> workers (164 registros)
-- Columnas origen: IdTrabajador, CvEmpresa, Clave, Nombre, Telefono, Tipo

INSERT INTO workers (id, company_code, employee_number, name, phone, worker_type, active, created_at) VALUES
  (gen_random_uuid(), 'THHHGO', '144', 'JHAIR AVENDAÑO POZO', '7715692800', 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3066', 'MERARI HERNANDEZ POZO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '213', 'REMEDIOS MORALES GUTIERREZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '207', 'PABLO LEI RODRIGUEZ LARIOS', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '241', 'ERNESTO GARCIA HERNANDEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '199', 'SANTIAGO YAÑEZ GODINEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '53', 'PEDRO GARCIA SANCHEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '149', 'JOSE LUIS GARCIA GOMEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '150', 'DULCE JULIETA AVENDAÑO JIMENEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '130', 'MARTHA IVONNE POZO MONTUFAR', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3054', 'ELIUB QUITZE BUSTAMANTE REYES', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3002', 'ERNESTO PARRA AGUILAR', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '75', 'CLAUDIA GUADALUPE CORONA MONTOYA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '232', 'SILVANO DOMINGUEZ DOMINGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '277', 'JULIO CESAR HERNANDEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '290', 'JUAN PABLO PEREZ MUCIÑO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3084', 'CLAUDIA LIZBETH SANCHEZ RAMIREZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '275', 'JOSE LUIS SANTIAGO AVENDAÑO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '209', 'RAFAEL AVENDAÑO MONTUFAR', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '261', 'ARTURO MARTINEZ VILLEDA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '227', 'MODESTO SEBASTIAN LEON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '3060', 'MIGUEL MUCIÑO HERNANDEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '204', 'ROSALINA ANGELES DONIS', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '195', 'LUIS JOSE AGUILAR CALDERON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '52', 'EUSEBIO BRAVO GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3099', 'VICTOR DAVID MAYA ARCE', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '257', 'ARMANDO MUCIÑO HERNANDEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3086', 'EDWIN BARUSH AVENDAÑO POZO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '235', 'JOSE FRANCISCO MENA BECERRIL', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '90', 'RODRIGO TOVAR CASTILLO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '279', 'JOSUE S. GUZMAN AGUILAR', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '283', 'MARILYN MEDINA JIMENEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '227', 'MODESTO SEBASTIAN LEON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '281', 'JUANA REYES CORONA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '252', 'PAULINO DE JESUS ROSAS', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '224', 'NORMA A. LARIOS JIMENEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '273', 'FRANCISCO GARCIA AGUILAR', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3008', 'BULMARO RODRIGUEZ RIVAS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3043', 'EDUARDO LEON LEON', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '292', 'FABIOLA AVENDAÑO SEBASTIAN', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3051', 'GABRIELA RODRIGUEZ JIMENEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3081', 'IRVING A. MUCIÑO MARTINEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3087', 'JUAN FCO. PARRA GARCÍA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3050', 'GRACIELA CHAVEZ HERNANDEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '227', 'MODESTO SEBASTIAN LEÓN', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), '3014', 'GJ', 'ERIC JOAQUIN CORTES', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3001', 'ARELI LOPEZ CORONA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3101', 'ARELY M. LOPEZ CORONA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3100', 'MILDRED ALISON MORALES GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '287', 'LAURA CORONA SANCHEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '208', 'LINO MUCIÑO PAZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '260', 'JUDITH SERRANO CRUZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3022', 'ADRIAN FLORES VAZQUEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '127', 'IVAN CRUZ JIMENEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '248', 'GILBERTO CORONA RODRIGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '263', 'RENE MARTINEZ OLGUIN', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '253', 'GABRIELA AVENDAÑO RESENDIZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '282', 'GREGORIO CORONA RODRIGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '236', 'SILVERIO AVENDAÑO BALLINAS', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3077', 'ERIC GIOVANNI CRUZ ORTEGA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '271', 'JACOBO PEREZ PEREZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '245', 'ALFREDO RODRIGUEZ REYES', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '249', 'EDUARDO BRAVO GARCIA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3013', 'JOSE ALFREDO OLGUIN LOPEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '139', 'IGNACIO SANCHEZ GONZALEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '258', 'JOSE LUIS MARTINEZ LOPEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3111', 'JESUS EMANUEL HERNANDEZ VALADEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '269', 'MA. ANTONIA MARTINEZ ALONSO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '259', 'JESUS RESENDIZ REYES', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '291', 'ANDRES OLGUIN BERNARDINO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '225', 'VICTOR MANUEL MAYA RODRIGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3080', 'JOCELYN OROPEZA MORALES', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '146', 'LUIS DANIEL SOSA DOROTEO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '295', 'DANIEL HERNANDEZ SANCHEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3079', 'JESSICA LILIANA LUGO RIVERA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '251', 'GABRIEL BUSTAMANTE CERON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3101', 'MAGALI LOPEZ CORONA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '191', 'LEOBARDO POZO MATURANO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '196', 'ANDRES CANO LOPEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3128', 'JORDAN ALBERTO GARCIA SERRANO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '117', 'GABRIEL RODRIGO CORONA HERNANDEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3106', 'ANA CRISTINA SANTIAGO GRANADOS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '293', 'JAVIER SEBASTIAN REYES', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'AGS', '638', 'PABLO ALEJANDRO RODRIGUEZ VAZQUEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3119', 'GABRIELA CABALLERO MORALES', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3044', 'VICTOR AMAURI LARIOS GALLEGOS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '247', 'EDUARDO BRAVO GARCIA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '2033', 'NAYELI JAZMIN RODRIGUEZ VAZQUEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '239', 'GERARDO RAMÍREZ OLGUÍN', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'PUE', '142', 'ALFONSO EMMANUEL GORDILLO PEREZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '274', 'ADELAIDO CORONA RAMIREZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3132', 'EDAIN SALVADOR MONTIEL ESTRADA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '249', 'FELIPE LOPEZ CASTILLO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3039', 'OSCAR AGUILAR GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '285', 'FIDENCIO LEON LEON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CA', '0', 'ING. NEREO GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3125', 'JESUS ALBERTO SANCHEZ VILLEDA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '289', 'HUGO SEBASTIAN MAQUEDA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JUB', '934', 'LORENZO PAZ MARTINEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '109', 'DANIEL MANUEL MUCIÑO CHAVEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '148', 'CRISTIAN DANAHI CORONA ALONSO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'AGS', '0', 'ANASTACIO REYES CORONA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '284', 'HECTOR AGUILAR GARCIA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '276', 'ANTONIO AGUILAR ARTEAGA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3123', 'LUIS FELIPE MARTINEZ LOPEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '262', 'JUAN BARRERA CRUZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3065', 'JUAN RAMON GARCIA MARTINEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '294', 'RICARDO MONDRAGON CERON', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '20', 'JESUS SERRANO ALCANTARA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '123', 'RUBICEL MORALES ROJAS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3110', 'JONATAN OTONIEL SANCHEZ RAMIREZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3129', 'VICTOR MANUEL CRUZ MONDRAGON', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3107', 'JUAN RAMON AVENDAÑO MAYA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '95', 'VICTOR MANUEL SANTILLANES SANCHEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3131', 'ALEXIS CRUZ GODINEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3056', 'ROBERTO BERNAL GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '278', 'JESUS SEBASTIAN PEÑA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3130', 'DONALDO MAYA AVENDAÑO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '231', 'JOSE LUIS MORALES ROJAS', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3091', 'DIEGO DE JESUS MIGUELES', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '237', 'J.GUADALUPE CHAVEZ ALONSO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '2018', 'ANA LAURA CORONA JIMENEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3088', 'JESUS HERNANDEZ AVENDAÑO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '25', 'ALEJANDRO RAMIREZ CRUZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '2037', 'DIANA VALERIA LIBREROS NIETO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3091', 'ELADIO BENITEZ GONZALEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '242', 'LUIS PARRA AGUILAR', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'PUE', '169', 'MIGUEL MONDRAGON CERON', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '125', 'ALEJANDRO OLGUIN BERNARDINO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '124', 'CESAR LEON LEON', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3092', 'ABRAHAM LARA AVENDAÑO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3015', 'ARISTEO CASTILLA VEGA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '22', 'JUSTINO GARCIA SANCHEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3111', 'JESUS EMANUEL HERNANDEZ V.', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3070', 'LUCERO BERENICE BRAVO SALAZAR', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '264', 'MACARIO CORONA SANCHEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '288', 'DANIEL GUERRERO GARCIA', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'PUE', '38', 'ISRAEL LOPEZ CASTILLO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '3061', 'JOSE ANDRES CANO CERON', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '270', 'MARTIN MONTIEL BUSTAMANTE', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '243', 'JOSE LUIS HERNANDEZ DOMINGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '116', 'HONORIO LUGO ALONSO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'GJ', '102', 'ALFREDO VEGA GARCIA', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '229', 'HECTOR CORONA HERNANDEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '3114', 'JULIO LUGO ALONSO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '0034', 'ENORE MUCIÑO LOPEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '078', 'VICTOR AMAURI LARIOS GALLEGOS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '084', 'MANUEL PAREDES TOVAR', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '0238', 'GUILLERMO MUCIÑO PAZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JOHGO', '6030', 'SERGIO GUADALUPE PALACIOS CHAVEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '120', 'JOSE FERNANDO CRUZ ABREGO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '225', 'VICTOR MANUEL MAYA RODRIGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '280', 'GONZALO PAREDES MARTINEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '248', 'GILBERTO CORONA RODRIGUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '254', 'MIGUEL ANGEL  LUNA MARQUEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '0081', 'GABRIEL RODRIGO  CORONA HERNANDEZ', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'COP', '286', 'JORGE ALBERTO YAÑEZ JIMENEZ', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), '001', 'EXT', 'JESUS PEREZ MUCIÑO', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '0009', 'OMAR SANTIAGO AVENDAÑO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '0083', 'FRANCISCO JAVIER CADENA SANDOVAL', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'CJ', '265', 'CORNELIO CRUZ URIBE', NULL, 'SOCIO', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '7008', 'RUBEN OMAR MERCADO MERCADO', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '007', 'ESPIRIDION MENDOZA MONTERROSAS', NULL, 'EVENTUAL', TRUE, NOW()),
  (gen_random_uuid(), 'JO', '6051', 'JESUS HERNANDEZ AVENDAÑO', NULL, 'EVENTUAL', TRUE, NOW());
